### ISSUE TITLE
Healthcheck does not work out of the box

### ISSUE THREAD

**Issue by 12345ieee** [gocd/helm-chart#106]
This is because by default it only listens on localhost, as specified here: https://docs.gocd.org/current/advanced_usage/agent-health-check-api.html , while kubernetes healthchecks come from external.

I can't figure out if there is an envvar I can set to have `go.agent.status.api.bind.host` be `0.0.0.0`, so I'm asking for help.

Once I have a setup that works I can make a PR to have `healthcheck.enabled` also turn on a wider host bind, so this works out of the box for everyone else.

**Comment by chadlwilson** [comment]
Can you give more detail on what evidence you have that this isn't working? The health API is part of liveness checks for static agent pods so they'd be constantly restarting if it wasn't working.

**Comment by chadlwilson** [comment]
Oh, I see, the liveness check isn't enabled in values by default - didn't realise that.

Anyway, to answer your original question, try something like 

`--set agent.env.goAgentJvmOpts=-Dgo.agent.status.api.bind.host=0.0.0.0`

**Comment by chadlwilson** [comment]
Thanks for raising. Pretty quick one, so done in `2.9.3`.

I'm not personally sure how useful are the agent health checks (and how sensibly tuned they are as to retries, allowing for expected server downtime during upgrades etc) given the way they are implemented, however that's a separate issue :-)

**Comment by 12345ieee** [comment]
Thank you very much, now it works out of the box.

I'm interested not much in the liveness part but mostly on the readiness, to recognize configuration or underlying infrastructure issues.
