### ISSUE TITLE
No symmetry in images versions

### ISSUE THREAD

**Issue by djkormo** [gocd/helm-chart#11]
Latest server  version is  v21.1.0

https://hub.docker.com/layers/gocd/gocd-server/v21.1.0/images/sha256-7d68a41ac2656d1ccf3e8426df7be0df7b92b4a5e49d28486642200fc6604c86?context=explore

Latest agent version  version is  v20.8.0

https://hub.docker.com/layers/gocd/gocd-agent-alpine-3.9/v20.8.0/images/sha256-3c7cd03a9c9b35451caadc7d99f5884243daa52154f00f17fedf0bdfcb7936af?context=explore

Template for sever

https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-server-deployment.yaml

          {{- if .Values.server.image.tag }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          {{- else }}
          image: "{{ .Values.server.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
		  
		  
		  
Template for agent

https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-agent-deployment.yaml

          {{- if .Values.agent.image.tag }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          {{- else }}
          image: "{{ .Values.agent.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
		  
		  
Default values		  
https://github.com/gocd/helm-chart/blob/master/gocd/values.yaml		  

for server 
  image:
    # server.image.repository is the GoCD Server image name
    repository: "gocd/gocd-server"
    # server.image.tag is the GoCD Server image's tag
    tag:
	
for agent

  image:
    # agent.image.repository is the GoCD Agent image name
    repository: "gocd/gocd-agent-alpine-3.9"
    # agent.image.tag is the GoCD Agent image's tag
    tag:	
	
If you don't controll deployed version via symmetry you should  not use Chart.AppVersion  for tag for both images.

**Comment by kritika-singh3** [comment]
Hello @djkormo, thanks for bringing this up. This happened as the `gocd/gocd-agent-alpine-3.9` was deprecated and removed in 20.9.0. I have updated the image to `gocd/gocd-agent-alpine-3.12` and created a release [gocd-1.36.0](https://github.com/gocd/helm-chart/releases/tag/gocd-1.36.0). Please test and verify.

**Comment by djkormo** [comment]
It works!

**Comment by djkormo** [comment]
Works
