### ISSUE TITLE
Can't deploy / SSL issues

### ISSUE THREAD

**Issue by nnsense** [gocd/helm-chart#12]
Hi
I've spent the last week trying to deploy this helm chart. The docs just mention to run `helm install gocd gocd/gocd --namespace gocd` but:

- That is by default deploying a NodePort on 8153 and an ingress with http which is then configured into the cluster config
- The agent complains it requires `https` as a connection
- I've deployed a Loadbalancer instead of the nodeport with TLS certs
- The agent complains that headers 'Content-MD5' and 'Cruise-Server-Ssl-Port' in response are missing
- Tried to configure the Ingress to use https without luck as no documentation is provided to match the values provided into this helm chart, same for an nginx controller.

Is it possible to have an hint on how to make this working? Thanks

**Comment by hokadiri** [comment]
https://github.com/gocd/gocd/issues/9279 should explain the issue you're having @nnsense

**Comment by chadlwilson** [comment]
As noted by @hokadiri there were some changes to TLS support. The error above might imply you are using really old agent versions and need updating to a version immediately prior to the changes.

If your agents are outside the cluster in which GoCD is running you will also need to tell them how to trust the cert issuer of your load balancer/ingress or (less recommended) disable TLS verification on your agents (like the below if you are deploying agents using the Helm chart).

```yaml
agent:
  env:
    goAgentBootstrapperArgs: '-sslVerificationMode NONE`
```

Will close this now as I don't think there is a fundamental issue with the chart and this is quite old now. Let me know if you are still having issues and I'll try and help.
