### ISSUE TITLE
Documentation/Customization Inquries

### ISSUE THREAD

**Issue by soudaburger** [gocd/helm-chart#14]
Hello!

First of all, this product looks great! I currently have it deployed in a GKE cluster with agents with very little effort, so thank you for building all of this!

Second, can you help me understand how I would do some of the following:
  1) Is there a way to get additional packages/applications into the agent containers?
  2) Is there a way to simply run custom k8s pods and/or containers  in order to run custom workflows?
  3) Is the `/go` that is required at the end of the `agent.env.goServerUrl` required?  The documentation around what this is for and how it should be constructed seems a bit sparse.

**Comment by arvindsv** [comment]
I'm not the best person to answer this, but I'll try:

1. I believe the accepted approach is a custom image and setting the: `agent.image.repository` property (mentioned [here](https://github.com/gocd/helm-chart/blob/master/gocd/README.md)).

2. Not sure. I don't think so.

3. Yes, it is. That's hard-coded unfortunately and cannot be changed. There was once an attempt to look into removing it, but it was too difficult.

**Comment by arvindsv** [comment]
Closing this, as it's not an issue. The conversation can continue, of course.
