### ISSUE TITLE
Support for multiple static agent containers

### ISSUE THREAD

**Issue by brettcurtis** [gocd/helm-chart#38]
Thinking it might be useful to have support for multiple static agents. For example, I have some workflows that need gocd/gocd-agent-ubuntu-20.04 and some that need to run docker so I need gocd/gocd-agent-docker-dind. I'm avoiding using elastic agents here as some persistence is needed for Gradle so workflows don't take so long. 

Am I looking at this wrong or is there a current way to solve my problem?

**Comment by chadlwilson** [comment]
To meet the direct requirement, you can install the chart again with a different release name and server disabled (multiple values files effectively). I think that would be the more canonical way to achieve such a thing in Helm.

In my previous setup we had agent-only uses of the chart and it worked fine. If there's anything that gets in the way of doing that we can probably address those issues pretty easily.

**Comment by brettcurtis** [comment]
Ok, that seems reasonable. I'll give it a go, thanks for the help!

**Comment by chadlwilson** [comment]
If you don't want to install and deploy two releases (so you can upgrade atomically), the other alternative might be to use a custom umbrella chart with an aliased dependency in Chart.yaml for the extra agent subchart. I haven't tried that with 2xgocd but should work.
