### ISSUE TITLE
Business Continuity support/example

### ISSUE THREAD

**Issue by MPV** [gocd/helm-chart#4]
Since the [Business Continuity](https://extensions-docs.gocd.org/business-continuity/current/) plugin has been open sourced, does this helm chart yet support easily running it?

If yes, would anyone be open to providing instructions or an example of how this can be done?

**Comment by MPV** [comment]
@GaneshSPatil / @arvindsv?

**Comment by arvindsv** [comment]
I don't really use Business Continuity, @MPV. I know there was a recent change in 20.9.0 which fixed this: https://github.com/gocd/gocd/issues/8630#issuecomment-708324217

Sorry, can't help much. Have you tried it? Business continuity is almost a "simple" combination of Postgres mirroring + a secondary GoCD server which is in standby. But, combining that with a helm chart / in k8s isn't something I've thought about.

**Comment by MPV** [comment]
For example, I'm curious whether BC could support upgrades of GoCD with less downtime.

**Comment by arvindsv** [comment]
My opinion: It would be unlikely to reduce downtime during an upgrade. It would be bad for the primary and the secondary to be too out of sync.

**Comment by chadlwilson** [comment]
Business continuity has been removed and likely not coming back.
